baseurl         = "/"
theme           = "casper-two"
languageCode    = "en-US"
disqusShortname = ""
paginate        = 6
#SectionPagesMenu = "main"

[params]
  title       = "Gordon's Blog"
  subtitle    = "Dev everywhere..."

  cover       = "img/cover.jpg"
  description = "Gordon Java Kotlin Python Docker Spring"
  metaDescription = ""
  #googleAnalytics = ""
  customCSS = []
  RSSLink = ""

  twitterName = "igordonxiao"
  #fbName = "igordonxiao"
  githubName = "igordonxiao"

  #logo = "hugo-logo.png"
  #orgName = "EM"
  #orgWebsite = "https://igordonxiao.github.io/"
  #orgDescription = "Gordon's Blog"

  author = "Gordon"
  authorAvatar = "img/avatar.jpeg"
  authorLocation = "Chengdu, China"
  authorWebsite = "https://igordonxiao.github.io/"
  authorDescription = "Web Developer"

  pageNotFoundTitle = "404 - Page not found"

  #casper or caspertwo
  singleViewStyle = "casper"

[permalinks]
  post = "/:slug/"

[[menu.main]]
  name = "主页"
  url = "/"
  weight = 200

[[menu.main]]
  name = "分类"
  url = "/categories"
  weight = 100

[[menu.main]]
  name = "标签"
  url = "/tags"
  weight = 99

[[menu.main]]
  name = "关于"
  url = "/about"
  weight = 95